### ISSUE TITLE
Move this board to ExaWind repo

### ISSUE THREAD

**Issue by pscrozi** [psakievich/hfm-fsi#104]

**Comment by pscrozi** [comment]
We might also want to organize these sub-project boards over on ExaWind.

**Comment by pscrozi** [comment]
Phil: we need to figure out how we want to manage the issues for this. Whether part of the Nalu repo or something separate. 

Mike: we can put issues wherever we want. We may want a private ExaWind-planning repo. We shouldn't have these on personal boards. They should be on ExaWind, whether private or public. 

Ganesh: we shouldn't even have this board in 3 months.

**Comment by pscrozi** [comment]
Phil: I created it, but haven't yet moved over the stories. Also made a planning repository.

**Comment by psakievich** [comment]
New Repository for issues: https://github.com/Exawind/hfm-fsi
Project board: https://github.com/orgs/Exawind/projects/13/views/1

**Comment by pscrozi** [comment]
Phil: we need to manually migrate these over, at least the active and to do. Phil will do this.

**Comment by psakievich** [comment]
I was able to transfer ownership of the old repository containing the issues to the exawind organization and I have updated the board for HLO, Todo and InProgress. I will keep the old project around for historical context but don't plan to migrate any of the other data.
