### ISSUE TITLE
Finish meshes

### ISSUE THREAD

**Issue by psakievich** [psakievich/hfm-fsi#13]
@gantech

**Comment by pscrozi** [comment]
NM80 mesh is done. Ganesh is trying it with FSI turned on.

NREL 5 MW is in process of uploading on Eagle.

IEA 15 MW hit a snag. Still needs more work. Issue with the tip of the blade. Ganesh can talk through it with people who want to. Shreyas Bidadi is off for 3 weeks.

**Comment by pscrozi** [comment]
Ganesh met with Nate yesterday. Nate pointed out some flaws in the mesh. Ganesh figured out a work-around. Now the mesh is easier to wrap up by noon today.

**Comment by pscrozi** [comment]
IAE 15 MW meshing will be resolved soon. 
NM80 mesh is working with FSI and controller on. Ganesh to launch the cases with input files from Ashesh.

**Comment by pscrozi** [comment]
IEA 15 MW done and being ported on 10/2. 
Should extrude easily. 
Area issue down from 400 to 4.
Eagle went down on Friday. Will have to get it from his docker. Ganesh will work with Nate on this at 11 a.m. today (10/2).

**Comment by pscrozi** [comment]
Met with Nate with 10/2. IEA 15 MW has been moved over to Nate.
