### ISSUE TITLE
Partially Complete Paper, part of Milestone FY23Q3 

### ISSUE THREAD

**Issue by kevmoor** [psakievich/hfm-fsi#15]
A skeleton draft, as a starting point has been drafted on the sandia overleaf here: http://overleaf.sandia.gov/3454322951txvgrzqsqvmn  It is just a draft to get things rolling and will likely be completely overhauled. That link should enable everyone to see and edit it, please let me know if that isn't the case since this internal overleaf instance is new, or if the team wants to do the draft a different way.

FY23 Q3: (Quarterly Progress Measure (Regular) - 2022-06-30) Create a repository with input files (OpenFAST, ExaWind-driver, Nalu-Wind, AMR-Wind) for blade-resolved Fluid-Structure Interaction (FSI) simulations in uniform inflow for three turbines that are important to the WETO portfolio: the NREL 5-MW turbine, the NM80 turbine, and the IEA 15-MW turbine. This will include details on performing FSI simulations with the tower on the NREL 5-MW turbine. Perform simulations of the IEA 15-MW turbine over the full power curve in uniform inflow and demonstrate expected behavior. The goal of this milestone is to harden the FSI code by exposing it to more scenarios and addressing any bugs that are detected in the process. The results from this milestone will be documented in the technical slides as part of the milestone completion **_along with a partially complete paper on FSI capabilities in ExaWind to be submitted to an appropriate journal at a later date_**.

**Comment by kevmoor** [comment]
May be a paper already that covers this? @ashesh2512 @gantech is there any planned or in process work on this?

**Comment by pscrozi** [comment]
Is there already a paper that covers this material? Not to this extent. Phil suggests that what we have is good enough.

**Comment by pscrozi** [comment]
For now, no need to do anything else on this. Waiting for runs to complete.

**Comment by psakievich** [comment]
Completed initial draft
